### ISSUE TITLE
Alternative forms for Khuen letters

### ISSUE THREAD

**Issue by r12a** [silnrsi/font-payap-lanna#7]
Thank you for providing a good looking font for Tai Tham! There is certainly a need for this.  I look forward to the day when it can be implemented using OpenType techology, so that it is generally available to web users.

However, i was a little surprised to see that the shapes remain the same whether the language of the text is set to nod or kkh.  I had been led to believe that the shapes of a few letters, such as the following differ in a pretty systematic way, depending on whether the underlying language is Northern Thai or Tai Khuen.

          ᨡ ᨢ ᨨ ᨪ ᨯ ᩋ

 ᨡ  U+1A21 TAI THAM LETTER HIGH KHA
ᨢ  U+1A22 TAI THAM LETTER HIGH KXA
ᨨ  U+1A28 TAI THAM LETTER HIGH CHA
ᨪ  U+1A2A TAI THAM LETTER LOW SA
ᨯ  U+1A2F TAI THAM LETTER DA
ᩋ  U+1A4B TAI THAM LETTER A

 I looked through the documentation and didn't see any information about font settings. Could you describe why the decision was made not to include such alternates?

**Comment by mhosken** [comment]
Yes this font doesn't support Khuen forms. This font is strongly lanna style and it would make no sense to have Khuen shapes, even optionally, in a font that is inappropriately styled for Khuen style Tai Tham. We're hoping one day we will have a proper Kheun font too. I also agree we would love to get OT working for this script.

This font is not aiming to provide full support for Tai Tham. It's target is Northern Thai, Lanna, which happens to be encoded in the Tai Tham block. As such it doesn't aim to provide technical support to those working on Tai Tham. It's to provide good quality Lanna.

**Comment by r12a** [comment]
Thanks for the clarification.  Note that the SIL page for this font says:

> Payap Lanna supports all languages that use the Tai Tham script, including Northern Thai, Tai Lue, and Khuen.

which is what got me wondering. It might be worth clarifying on that page somewhere.

**Comment by jvgaultney** [comment]
I'll clarify that - thanks

**Comment by jvgaultney** [comment]
Done I think

**Comment by r12a** [comment]
LGTM, thanks.
